### ISSUE TITLE
Clear description of the project for SLOP applicants

### ISSUE THREAD

**Issue by Rukmini-Meda** [adithyaanilkumar/women_safety#15]
A clear description of the project in the README.md will help SLOP applicants while preparing the proposal. The description can include the objectives of the project, how does it work, how to set up and details if any for SLOP applicants. I am interested in contributing to this project as part of SLOP. Hence, it will be useful if the README is updated

**Comment by Rukmini-Meda** [comment]
> A clear description of the project in the README.md will help SLOP applicants while preparing the proposal. The description can include the objectives of the project, how does it work, how to set up and details if any for SLOP applicants. I am interested in contributing to this project as part of SLOP. Hence, it will be useful if the README is updated

@adithyaanilkumar

**Comment by adithyaanilkumar** [comment]
Definitely. I will update this ASAP.

**Comment by adithyaanilkumar** [comment]
Have updated the Description of the project and will be providing a detailed documentation of the project within  a week of time. For now this is sufficient for participants to get started with the project.
